// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TDPCompetitions.Infrastracture.Data;

#nullable disable

namespace TDPCompetitions.Infrastracture.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrivacyAttachmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrivacyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RankingsVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("RegistrationsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrivacyAttachmentId");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Competitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressProvince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthProvince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("GuardianOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMinor")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MinorRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("MinorRegistrationId");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProblemGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProblemGroupId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.ProblemsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("ProblemsGroups");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CompetitorId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.SentProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SentProblems");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.SentSpecialProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SpecialProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SentSpecialProblems");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.SpecialProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("SpecialProblems");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Competition", b =>
                {
                    b.HasOne("TDPCompetitions.Core.Entities.File", "PrivacyAttachment")
                        .WithMany()
                        .HasForeignKey("PrivacyAttachmentId");

                    b.Navigation("PrivacyAttachment");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Competitor", b =>
                {
                    b.HasOne("TDPCompetitions.Core.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDPCompetitions.Core.Entities.Registration", null)
                        .WithMany("Minors")
                        .HasForeignKey("MinorRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Problem", b =>
                {
                    b.HasOne("TDPCompetitions.Core.Entities.ProblemsGroup", "Group")
                        .WithMany("Problems")
                        .HasForeignKey("ProblemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.ProblemsGroup", b =>
                {
                    b.HasOne("TDPCompetitions.Core.Entities.Competition", "Competition")
                        .WithMany("ProblemGroups")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Registration", b =>
                {
                    b.HasOne("TDPCompetitions.Core.Entities.Competition", "Competition")
                        .WithMany("Registrations")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDPCompetitions.Core.Entities.Competitor", "Competitor")
                        .WithOne("Registration")
                        .HasForeignKey("TDPCompetitions.Core.Entities.Registration", "CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Competitor");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.SpecialProblem", b =>
                {
                    b.HasOne("TDPCompetitions.Core.Entities.Competition", "Competition")
                        .WithMany("SpecialProblems")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Competition", b =>
                {
                    b.Navigation("ProblemGroups");

                    b.Navigation("Registrations");

                    b.Navigation("SpecialProblems");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Competitor", b =>
                {
                    b.Navigation("Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.ProblemsGroup", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("TDPCompetitions.Core.Entities.Registration", b =>
                {
                    b.Navigation("Minors");
                });
#pragma warning restore 612, 618
        }
    }
}
